// Categories
export const CHANGE_CATEGORY = "CHANGE_CATEGORY"
export const GET_CATEGORİES_SUCCESS = "GET_CATEGORİES_SUCCESS"

// Products
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"

// Cart
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"